// Copyright 2026 G&G Technologies S.r.l. — SPDX-License-Identifier: Apache-2.0

// Written by hand, and short on purpose: this is the one delicate piece of the whole app, and the
// one you least want generated by a plugin nobody read.
//
// Rules it obeys, from app/CLAUDE.md:
//  - scope stays inside /app/spronia/run/, so no page of the site can ever be served from here;
//  - the cache name carries the version, and everything else is deleted on activate;
//  - sw.js never caches itself;
//  - no skipWaiting and no clients.claim: an update lands at the next start. Swapping files under
//    a running app means changing the code while somebody is halfway through a game.

const VERSION = '0.40.0';
const CACHE = `spronia-v${VERSION}`;

// Every file the app is made of, plus the shared modules it borrows. Kept by hand and checked by
// _src/check_apps.py against the two directories, rather than generated: a checked list keeps the
// served file identical to the source, which is the whole point of having no build step.
//
// No `?v=` on any of them, deliberately. The version lives in the cache name, which is replaced
// whole on activate, so the set is always internally consistent — a half-done versioning scheme on
// part of the files is worse than none at all.
const ASSETS = [
  './',
  './index.html',
  './styles.css',
  './app.js',
  './i18n.js',
  './game.js',
  './terrain.js',
  './waves.js',
  './render.js',
  './sprites.js',
  './input.js',
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png',
  './icon-maskable-512.png',
  // The shared library. Written out in full because a service worker does not see the import map
  // of the page: this is the one place where the path to _lib/ appears a second time, and
  // check_apps.py exists to keep the two saying the same thing.
  '../../_lib/base.css',
  '../../_lib/i18n.js',
  '../../_lib/theme.js',
  '../../_lib/install.js',
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) => Promise.all(
      names.filter((name) => name !== CACHE).map((name) => caches.delete(name)),
    )),
  );
});

// Cache first, and no network fallback beyond the plain fetch: the app has nothing to fetch from
// anywhere else, and a fetch handler is also one of the conditions for being installable.
//
// The shared library sits at /app/_lib/, outside this worker's scope, and is served from here all
// the same. Worth writing down because the obvious reading is the wrong one: the scope decides
// which *pages* this worker controls, not which requests it sees. Once it controls the page in
// run/, every request that page makes passes through here — the modules one directory up included.
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (url.pathname.endsWith('/sw.js')) return;

  event.respondWith(
    caches.match(event.request, { ignoreSearch: false }).then((hit) => hit || fetch(event.request)),
  );
});
