// Copyright 2026 G&G Technologies S.r.l. — SPDX-License-Identifier: Apache-2.0

// Written by hand, and short on purpose: this is the one delicate piece of the whole app, and the
// one you least want generated by a plugin nobody read.
//
// Rules it obeys, from app/CLAUDE.md:
//  - scope stays inside /app/plan-scope/run/, so no page of the site can ever be served from here;
//  - the cache name carries the version, and everything else is deleted on activate;
//  - sw.js never caches itself;
//  - no skipWaiting on its own and no clients.claim: an update lands at the next start, or
//    when the person presses «Aggiorna» on the line gg/update.js shows. Swapping files under a
//    running app means changing the code while somebody has unsaved keystrokes in a page, and
//    saving them one reload is not worth that.

const VERSION = '4.15.2';
const CACHE = `plan-scope-v${VERSION}`;

// La cache dei promemoria, e **l'unica che sopravvive a un aggiornamento**. Il nome non porta la
// versione apposta: dentro c'è il digest che `gg/remind.js` scrive dalla pagina — le scadenze con
// il momento in cui vanno dette, già calcolato — e buttarlo a ogni versione nuova spegnerebbe le
// sveglie proprio nel giorno in cui l'app cambia, senza che nessuno l'abbia chiesto. Il nome deve
// restare `<chiave dell'app>-remind`: lo stesso che `remind.notes()` costruisce dall'altra parte,
// e `check_apps.py` controlla che i due dicano la stessa cosa.
const NOTES = 'plan-scope-remind';
const DIGEST = './gg-digest';

// Every file the app is made of. Kept by hand and checked by _src/check_apps.py against the
// directory listing, rather than generated: a checked list keeps the served file identical to the
// source, which is the whole point of having no build step.
//
// No `?v=` on any of them, and that is deliberate. A partial cache-busting scheme is worse than
// none: it hides the problem it pretends to fix. The version lives in the cache name instead, and
// on activate the whole cache is replaced, so the set is always internally consistent.
const ASSETS = [
  './',
  './index.html',
  './styles.css',
  './app.js',
  './i18n.js',
  './db.js',
  './home.js',
  './plan.js',
  './timeline.js',
  './templates.js',
  './demo.js',
  './cheer.js',
  './search.js',
  './csv.js',
  './webpage.js',
  './diff.js',
  './importers.js',
  './outputs.js',
  './versions.js',
  './pages.js',
  './importing.js',
  './vault.js',
  './sync.js',
  './folders.js',
  './backup.js',
  './ui.js',
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png',
  './icon-maskable-512.png',
  // The shared library. Written out in full because a service worker does not see the page's
  // import map: this is the one place where the path to _lib/ appears a second time, and
  // check_apps.py exists to keep the two saying the same thing.
  '../../_lib/base.css',
  '../../_lib/i18n.js',
  '../../_lib/theme.js',
  '../../_lib/install.js',
  '../../_lib/update.js',
  '../../_lib/store.js',
  '../../_lib/io.js',
  '../../_lib/zip.js',
  '../../_lib/folder.js',
  '../../_lib/plan-markdown.js',
  '../../_lib/plan-editor.js',
  '../../_lib/plan-editor.css',
  '../../_lib/clip.js',
  '../../_lib/dom.js',
  '../../_lib/plan-pack.js',
  '../../_lib/plan-model.js',
  '../../_lib/remind.js',
  '../../_lib/ics.js',
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) => Promise.all(
      names.filter((name) => name !== CACHE && name !== NOTES).map((name) => caches.delete(name)),
    )),
  );
});

// Cache first, and no network fallback beyond the plain fetch: the app has nothing to fetch from
// anywhere else, and a fetch handler is also one of the conditions for being installable.
//
// The shared library sits at /app/_lib/, outside this worker's scope, and is served from here all
// the same. Worth writing down because the obvious reading is the wrong one: the scope decides
// which *pages* this worker controls, not which requests it sees. Once it controls the page in
// run/, every request that page makes passes through here — including the modules one directory up
// — so the library is cached and served offline like everything else.
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (url.pathname.endsWith('/sw.js')) return;

  // A navigation gets the app's page whatever the query string says. The app keeps where you are in
  // the address — `?v=page&p=…` — and a cache keyed on the full URL held none of those: offline,
  // reloading any screen but the archive went to the network and got the browser's error page.
  // Installed, that was every resume after having navigated anywhere.
  if (event.request.mode === 'navigate') {
    event.respondWith(caches.match('./').then((hit) => hit || fetch(event.request)));
    return;
  }

  event.respondWith(
    caches.match(event.request, { ignoreSearch: true }).then((hit) => hit || fetch(event.request)),
  );
});

// The two messages `gg/update.js` sends: which version this worker is, and — from the person's
// click on «Aggiorna», never on its own — the go-ahead to take over from the one before it.
self.addEventListener('message', (event) => {
  const type = event.data && event.data.type;
  if (type === 'gg:version' && event.ports && event.ports[0]) event.ports[0].postMessage(VERSION);
  if (type === 'gg:skip-waiting') self.skipWaiting();
});

// ---- i promemoria ------------------------------------------------------------------------------
//
// **Questo worker non sa cos'è una scadenza.** La pagina gli lascia una lista di `{ key, when,
// text }` con il momento già calcolato e la frase già scritta nella lingua giusta; qui si
// confrontano due stringhe ISO e si segna cosa è stato detto. Nessun modello, nessun database,
// nessuna traduzione: le tre cose che, in un file che gira mentre nessuno guarda, non si possono
// né provare né vedere fallire.
//
// `periodicsync` esiste su Chromium e con l'app installata, e la frequenza la decide il browser.
// Dove non c'è, la pagina dice le stesse cose all'apertura: è il motivo per cui questo blocco può
// essere così piccolo e non deve promettere niente.

async function announce() {
  const cache = await caches.open(NOTES);
  const hit = await cache.match(new Request(DIGEST));
  if (!hit) return;

  const saved = await hit.json();
  if (!saved || !saved.on) return;

  const now = new Date().toISOString();
  const said = new Set(saved.said || []);
  const due = (saved.items || []).filter((one) => one.when <= now && !said.has(one.key));
  if (!due.length) return;

  // Una notifica sola, anche per cinque scadenze: cinque avvisi impilati sono cinque cose da
  // togliere di mezzo, e chi li toglie non legge la quinta.
  const body = due.length === 1
    ? due[0].text
    : due.slice(0, 3).map((one) => one.text).join('\n');
  await self.registration.showNotification(saved.heading || 'Plan Scope', {
    body,
    tag: 'gg:due',
    icon: './icon-192.png',
    badge: './icon-192.png',
    data: { count: due.length },
  });

  for (const one of due) said.add(one.key);
  await cache.put(new Request(DIGEST), new Response(JSON.stringify({ ...saved, said: [...said] }),
    { headers: { 'Content-Type': 'application/json' } }));
}

self.addEventListener('periodicsync', (event) => {
  if (event.tag === 'gg:due') event.waitUntil(announce());
});

// Un clic sulla notifica apre l'app se è chiusa, e porta in primo piano quella che c'è già: due
// finestre della stessa app aperte da un avviso sono un avviso che ha fatto danno.
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil((async () => {
    const open = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    for (const client of open) {
      if (client.url.includes('/app/plan-scope/run/') && 'focus' in client) return client.focus();
    }
    if (self.clients.openWindow) return self.clients.openWindow('./');
    return undefined;
  })());
});
