// Copyright 2026 G&G Technologies S.r.l. — SPDX-License-Identifier: Apache-2.0

// Written by hand, and short on purpose: it is the only delicate piece of the whole app, and the one
// you least want generated by a plugin you have not read.
//
// The rules it keeps, from app/CLAUDE.md:
//  - the scope stays inside /app/recinto/run/, so no page of the site can ever be served from here;
//  - the cache name carries the version, and everything else is deleted on activate;
//  - sw.js never caches itself;
//  - no skipWaiting on its own initiative and no clients.claim: an update arrives at the next
//    start. Swapping the files under a running app means changing the code under somebody who is
//    halfway through a game.

const VERSION = '0.15.3';
const CACHE = `recinto-v${VERSION}`;

// Every file the app is made of, plus the shared modules it borrows. Kept by hand and checked by
// _src/check_apps.py against the two folders, rather than generated: a checked list keeps the
// served file identical to the source, which is the whole point of having no build step.
//
// No `?v=` on any of them, on purpose. The version lives in the cache name, which is replaced whole
// on activate, so the set is always consistent with itself — versioning done halfway, on some of
// the files, is worse than none.
const ASSETS = [
  './',
  './index.html',
  './styles.css',
  './app.js',
  './i18n.js',
  './game.js',
  './geometry.js',
  './arenas.js',
  './render.js',
  './input.js',
  './audio.js',
  './haptics.js',
  './scores.js',
  './attract.js',
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png',
  './icon-maskable-512.png',
  // The shared library, spelt out in full because a service worker cannot see the page's import
  // map: this is the only place where the _lib/ path appears a second time, and check_apps.py exists
  // to keep the two saying the same thing.
  '../../_lib/base.css',
  '../../_lib/dom.js',
  '../../_lib/i18n.js',
  '../../_lib/theme.js',
  '../../_lib/install.js',
  '../../_lib/update.js',
  '../../_lib/store.js',
  '../../_lib/io.js',
];

// **Every file is taken from the network, not from the browser's cache.**
//
// `cache.addAll` makes ordinary fetches, and an ordinary fetch honours the HTTP cache. With a
// ten-minute `max-age` — what any static host sets — a new worker installing shortly after a release
// fills up with the **old** files, which are still fresh in there. The only one that escapes is
// `sw.js`, because the browser always rechecks that one by itself.
//
// The effect is the worst an update can have: **the app announces the new version and runs the old
// code**, because the version number comes from this very file. Measured, not feared: in a test, the
// cache named after the new version held the files of the previous one.
//
// `cache: 'reload'` takes the HTTP cache out of the way for these files, once, at install time.
self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then(
    (cache) => cache.addAll(ASSETS.map((url) => new Request(url, { cache: 'reload' })))));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) => Promise.all(
      names.filter((name) => name !== CACHE).map((name) => caches.delete(name)),
    )),
  );
});

// Cache first, and the network only for what is not there. The app has nothing to ask of anybody:
// if one day it did ask for something, that something would be a defect, not a resource.
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.match(event.request).then((hit) => hit || fetch(event.request)),
  );
});

// The two things the page asks for, and they are the only ones.
//
// `gg:version` is the one I had forgotten: `gg/update.js` asks **the worker** for the version, not
// the page, because the version lives here and nowhere else. Without an answer the badge under the
// app's name stays empty — a visible button that says nothing — and no error reports it, because a
// question with no answer is not an exception.
//
// `gg:skip-waiting` is the swap, and it arrives only if somebody presses. Never on the worker's own
// initiative: changing the files under a running app means changing the code under somebody who is
// halfway through a game.
self.addEventListener('message', (event) => {
  const type = event.data && event.data.type;
  if (type === 'gg:version' && event.ports && event.ports[0]) event.ports[0].postMessage(VERSION);
  if (type === 'gg:skip-waiting') self.skipWaiting();
});
