// Copyright 2026 G&G Technologies S.r.l. — SPDX-License-Identifier: Apache-2.0

// Written by hand, and short on purpose: this is the one delicate piece of the whole app, and the
// one you least want generated by a plugin nobody read.
//
// Rules it obeys, from app/CLAUDE.md:
//  - scope stays inside /app/invoice-scope/run/, so no page of the site is ever served from here;
//  - the cache name carries the version, and everything else is deleted on activate;
//  - sw.js never caches itself;
//  - no skipWaiting on its own and no clients.claim: an update lands at the next start, or
//    when the person presses «Aggiorna» on the line gg/update.js shows. Swapping files under
//    a running app means changing the code while somebody is halfway through an invoice, and
//    saving them one reload is not worth that — here least of all.

const VERSION = '0.29.2';
const CACHE = `invoice-scope-v${VERSION}`;

// Every file the app is made of. Kept by hand and checked by _src/check_apps.py against the
// directory listing, rather than generated: a checked list keeps the served file identical to the
// source, which is the whole point of having no build step.
//
// No `?v=` on any of them. The version lives in the cache name instead: on activate the whole
// cache is replaced, so the set is always internally consistent.
const ASSETS = [
  './',
  './index.html',
  './styles.css',
  './print.css',
  './app.js',
  './ask.js',
  './backup.js',
  './brand.js',
  './db.js',
  './doc.js',
  './due.js',
  './decimal.js',
  './demo.js',
  './fatturapa.js',
  './fic.js',
  './format.js',
  './i18n.js',
  './importing.js',
  './kinds.js',
  './memory.js',
  './model.js',
  './parse.js',
  './parties.js',
  './payments.js',
  './print.js',
  './problems.js',
  './reading.js',
  './schedule.js',
  './sheet.js',
  './states.js',
  './timeline.js',
  './totals.js',
  './validate.js',
  './xml.js',
  './xls.js',
  './xmlread.js',
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png',
  './icon-maskable-512.png',
  // The shared library. Written out in full because a service worker does not see the page's
  // import map: this is the one place where the path to _lib/ appears a second time, and
  // check_apps.py exists to keep the two saying the same thing.
  '../../_lib/base.css',
  '../../_lib/i18n.js',
  '../../_lib/theme.js',
  '../../_lib/install.js',
  '../../_lib/update.js',
  '../../_lib/store.js',
  '../../_lib/io.js',
  '../../_lib/zip.js',
  '../../_lib/folder.js',
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) => Promise.all(
      names.filter((name) => name !== CACHE).map((name) => caches.delete(name)),
    )),
  );
});

// Cache first, and no network fallback beyond the plain fetch: the app has nothing to fetch from
// anywhere else, and a fetch handler is also one of the conditions for being installable.
//
// The shared library sits at /app/_lib/, outside this worker's scope, and is served from here all
// the same. Worth writing down because the obvious reading is the wrong one: the scope decides
// which *pages* this worker controls, not which requests it sees. Once it controls the page in
// run/, every request that page makes passes through here — including the modules one directory
// up — so the library is cached and served offline like everything else.
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (url.pathname.endsWith('/sw.js')) return;

  event.respondWith(
    caches.match(event.request, { ignoreSearch: false }).then((hit) => hit || fetch(event.request)),
  );
});

// The two messages `gg/update.js` sends: which version this worker is, and — from the person's
// click on «Aggiorna», never on its own — the go-ahead to take over from the one before it.
self.addEventListener('message', (event) => {
  const type = event.data && event.data.type;
  if (type === 'gg:version' && event.ports && event.ports[0]) event.ports[0].postMessage(VERSION);
  if (type === 'gg:skip-waiting') self.skipWaiting();
});
