// Copyright 2026 G&G Technologies S.r.l. — SPDX-License-Identifier: PolyForm-Shield-1.0.0

// Written by hand, and short on purpose: this is the one delicate piece of the whole app, and the
// one you least want generated by a plugin nobody read.
//
// Rules it obeys, from app/CLAUDE.md:
//  - scope stays inside /app/survey-scope/run/, so no page of the site can ever be served from here;
//  - the cache name carries the version, and everything else is deleted on activate;
//  - sw.js never caches itself;
//  - no skipWaiting on its own and no clients.claim: an update lands at the next start, or
//    when the person presses «Aggiorna» on the line gg/update.js shows. Swapping files under a
//    running app means changing the questionnaire while somebody is half way through answering it,
//    and saving them one reload is not worth an edition that changes under their hands.

const VERSION = '1.31.0';
const CACHE = `survey-scope-v${VERSION}`;

// Every file the app is made of. Kept by hand and checked by _src/check_apps.py against the
// directory listing, rather than generated: a checked list keeps the served file identical to the
// source, which is the whole point of having no build step.
//
// The four JSON files are in here like everything else, and they are not data the app fetches from
// somewhere — they *are* the questionnaire, the same copy the Python tools read. Leaving them out
// would give an installed app a working interface and no questions in it.
//
// No `?v=` on any of them, and that is deliberate. A partial cache-busting scheme is worse than
// none: it hides the problem it pretends to fix. The version lives in the cache name instead, and
// on activate the whole cache is replaced, so the set is always internally consistent.
const ASSETS = [
  './',
  './index.html',
  './styles.css',
  './app.js',
  './i18n.js',
  './content.js',
  './score.js',
  './report.js',
  './export.js',
  './pack.js',
  './ai-maturity/questionnaire-1.json',
  './ai-maturity/report-1.json',
  './ai-maturity/compliance-1.json',
  './ai-maturity/deepdive-1.json',
  // Il secondo questionario. **Niente approfondimento**: non tutti i questionari hanno
  // tutti i moduli, e `content.js` passa `null` dove il file non c'è.
  './nis2/questionnaire-1.json',
  './nis2/report-1.json',
  './nis2/compliance-1.json',
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png',
  './icon-maskable-512.png',
  // The shared libraries. Written out in full because a service worker does not see the page's
  // import map: this is the one place where the paths to _lib/ and _business/ appear a second
  // time, and check_apps.py exists to keep the two saying the same thing.
  '../../_lib/base.css',
  '../../_lib/i18n.js',
  '../../_lib/theme.js',
  '../../_lib/install.js',
  '../../_lib/update.js',
  '../../_lib/store.js',
  '../../_lib/io.js',
  '../../_business/folder.js',
];

// **Every file is taken from the network, not from the browser's cache.**
//
// `cache.addAll` makes ordinary fetches, and an ordinary fetch honours the HTTP cache. With a
// ten-minute `max-age` — what any static host sets — a new worker installing shortly after a release
// fills up with the **old** files, which are still fresh in there. The only one that escapes is
// `sw.js`, because the browser always rechecks that one by itself.
//
// The effect is the worst an update can have: **the app announces the new version and runs the old
// code**, because the version number comes from this very file. Measured, not feared: in a test, the
// cache named after the new version held the files of the previous one.
//
// `cache: 'reload'` takes the HTTP cache out of the way for these files, once, at install time.
self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then(
    (cache) => cache.addAll(ASSETS.map((url) => new Request(url, { cache: 'reload' })))));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) => Promise.all(
      names.filter((name) => name !== CACHE).map((name) => caches.delete(name)),
    )),
  );
});

// Cache first, and no network fallback beyond the plain fetch: the app has nothing to fetch from
// anywhere else, and a fetch handler is also one of the conditions for being installable.
//
// The shared libraries sit at /app/_lib/ and /app/_business/, outside this worker's scope, and are
// served from here all the same. Worth writing down because the obvious reading is the wrong one:
// the scope decides which *pages* this worker controls, not which requests it sees. Once it
// controls the page in run/, every request that page makes passes through here — including the
// modules one directory up — so the library is cached and served offline like everything else.
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (url.pathname.endsWith('/sw.js')) return;

  event.respondWith(
    caches.match(event.request, { ignoreSearch: false }).then((hit) => hit || fetch(event.request)),
  );
});

// The two messages `gg/update.js` sends: which version this worker is, and — from the person's
// click on «Aggiorna», never on its own — the go-ahead to take over from the one before it.
self.addEventListener('message', (event) => {
  const type = event.data && event.data.type;
  if (type === 'gg:version' && event.ports && event.ports[0]) event.ports[0].postMessage(VERSION);
  if (type === 'gg:skip-waiting') self.skipWaiting();
});
