// Copyright 2026 G&G Technologies S.r.l. — SPDX-License-Identifier: Apache-2.0

// Written by hand, and short on purpose: this is the one delicate piece of the whole app, and the
// one you least want generated by a plugin nobody read.
//
// Rules it obeys, from app/CLAUDE.md:
//  - scope stays inside /app/survey-scope/run/, so no page of the site can ever be served from here;
//  - the cache name carries the version, and everything else is deleted on activate;
//  - sw.js never caches itself;
//  - no skipWaiting and no clients.claim: an update lands at the next start. Swapping files under a
//    running app means changing the questionnaire while somebody is half way through answering it,
//    and saving them one reload is not worth an edition that changes under their hands.

const VERSION = '1.27.2';
const CACHE = `survey-scope-v${VERSION}`;

// Every file the app is made of. Kept by hand and checked by _src/check_apps.py against the
// directory listing, rather than generated: a checked list keeps the served file identical to the
// source, which is the whole point of having no build step.
//
// The four JSON files are in here like everything else, and they are not data the app fetches from
// somewhere — they *are* the questionnaire, the same copy the Python tools read. Leaving them out
// would give an installed app a working interface and no questions in it.
//
// No `?v=` on any of them, and that is deliberate. A partial cache-busting scheme is worse than
// none: it hides the problem it pretends to fix. The version lives in the cache name instead, and
// on activate the whole cache is replaced, so the set is always internally consistent.
const ASSETS = [
  './',
  './index.html',
  './styles.css',
  './app.js',
  './i18n.js',
  './content.js',
  './score.js',
  './report.js',
  './export.js',
  './pack.js',
  './ai-maturity/questionnaire-1.json',
  './ai-maturity/report-1.json',
  './ai-maturity/compliance-1.json',
  './ai-maturity/deepdive-1.json',
  // Il secondo questionario. **Niente approfondimento**: non tutti i questionari hanno
  // tutti i moduli, e `content.js` passa `null` dove il file non c'è.
  './nis2/questionnaire-1.json',
  './nis2/report-1.json',
  './nis2/compliance-1.json',
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png',
  './icon-maskable-512.png',
  // The shared library. Written out in full because a service worker does not see the page's
  // import map: this is the one place where the path to _lib/ appears a second time, and
  // check_apps.py exists to keep the two saying the same thing.
  '../../_lib/base.css',
  '../../_lib/i18n.js',
  '../../_lib/theme.js',
  '../../_lib/install.js',
  '../../_lib/store.js',
  '../../_lib/io.js',
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) => Promise.all(
      names.filter((name) => name !== CACHE).map((name) => caches.delete(name)),
    )),
  );
});

// Cache first, and no network fallback beyond the plain fetch: the app has nothing to fetch from
// anywhere else, and a fetch handler is also one of the conditions for being installable.
//
// The shared library sits at /app/_lib/, outside this worker's scope, and is served from here all
// the same. Worth writing down because the obvious reading is the wrong one: the scope decides
// which *pages* this worker controls, not which requests it sees. Once it controls the page in
// run/, every request that page makes passes through here — including the modules one directory up
// — so the library is cached and served offline like everything else.
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (url.pathname.endsWith('/sw.js')) return;

  event.respondWith(
    caches.match(event.request, { ignoreSearch: false }).then((hit) => hit || fetch(event.request)),
  );
});
