// Copyright 2026 G&G Technologies S.r.l. — SPDX-License-Identifier: Apache-2.0

// Written by hand, and short on purpose: this is the one delicate piece of the whole app, and the
// one you least want generated by a plugin nobody read.
//
// Rules it obeys, from app/CLAUDE.md:
//  - scope stays inside /app/csv-scope/run/, so no page of the site can ever be served from here;
//  - the cache name carries the version, and everything else is deleted on activate;
//  - sw.js never caches itself;
//  - no skipWaiting and no clients.claim: an update lands at the next start. Swapping files under
//    a running app means changing the code while somebody has an open file and a live selection,
//    and saving them one reload is not worth that.

const VERSION = '0.12.0';
const CACHE = `csv-scope-v${VERSION}`;

// Every file the app is made of. Kept by hand and checked by _src/check_apps.py against the
// directory listing, rather than generated: a checked list keeps the served file identical to the
// source, which is the whole point of having no build step.
//
// No `?v=` on any of them, and that is deliberate. An earlier version marked only styles.css and
// app.js, leaving six modules unmarked — so a renamed export in chart.js was served stale while
// the page looked freshly versioned, which is worse than no scheme at all. The version lives in
// the cache name instead: on activate the whole cache is replaced, so the set is always internally
// consistent. `check_apps.py` refuses a query string here for that reason.
const ASSETS = [
  './',
  './index.html',
  './styles.css',
  './app.js',
  './i18n.js',
  './csv.js',
  './stats.js',
  './chart.js',
  './table.js',
  './theme.js',
  './install.js',
  './store.js',
  './io.js',
  './history.js',
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png',
  './icon-maskable-512.png',
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) => Promise.all(
      names.filter((name) => name !== CACHE).map((name) => caches.delete(name)),
    )),
  );
});

// Cache first, and no network fallback beyond the plain fetch: the app has nothing to fetch from
// anywhere else, and a fetch handler is also one of the conditions for being installable.
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (url.pathname.endsWith('/sw.js')) return;

  event.respondWith(
    caches.match(event.request, { ignoreSearch: false }).then((hit) => hit || fetch(event.request)),
  );
});
